# Site settings
title: Navigating the Digital Economy
description: >-
  Personal website of Pablo Lanaspa. I write about product management, platforms, and the digital economy.
baseurl: ""
url: "https://planaspa.com"
lang: en
twitter:
  username: planaspa
  card: summary_large_image

social:
  twitter: planaspa
  linkedin: planaspa
  email: info@planaspa.com

author:
  name: Pablo Lanaspa Ferrer
  image: bio_img.png

# Google Analytics 4 (leave blank to disable)
google_analytics: G-6SDG48R4SK

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  - scope:
      path: "_pages"
    values:
      layout: page
      permalink: /:basename/
  - scope:
      path: "_pages/tag-redirects"
    values:
      layout: null
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gemini
  - vendor
  - .bundle

sass:
  sass_dir: _sass
  style: compressed
