# Site settings
title: Surcando la economía digital
description: >-
  Sitio web personal de Pablo Lanaspa. Publico opiniones personales acerca de la economía digital.
baseurl: ""
url: "https://planaspa.com"
twitter_username: planaspa

author:
  name: Pablo Lanaspa Ferrer
  image: bio_img.jpg

# Google Analytics (leave blank to disable)
google_analytics:

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
