# Site settings
title: Surcando la economía digital
description: >-
  Sitio web personal de Pablo Lanaspa. Publico opiniones personales acerca de la economía digital.
baseurl: ""
url: "https://planaspa.com"
lang: en
twitter:
  username: planaspa
  card: summary_large_image

author:
  name: Pablo Lanaspa Ferrer
  image: bio_img.png

# Google Analytics 4 (leave blank to disable)
google_analytics: G-6SDG48R4SK

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

defaults:
  - scope:
      path: "_pages"
    values:
      layout: page
      permalink: /:basename/
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gemini
  - scripts
  - vendor
  - .bundle

# Tags (local builds only unless using a custom GitHub Actions workflow)
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed
